services:
  biosmb-rl:
    build: .
    container_name: biosmb-rl-controller
    volumes:
      - models:/app/models
      - logs:/app/logs
      - ./main.py:/app/main.py    # if we want to edit main file without recreating docker image (connects to local main file)   
      # - root:/app        
    restart: unless-stopped

volumes:
  models:
    external: false
  logs:
    external: false
  # root:
  #   external: false
